tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/science'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'jiritrecak/laurine'

brew 'antigen'
brew 'openssl'
brew 'asciinema'
brew 'bash'
brew 'bash-completion@2'
brew 'git'
brew 'carthage'
brew 'gnupg'
brew 'gnupg@1.4'
brew 'go'
brew 'httpie'
brew 'hugo'
brew 'jq'
brew 'llvm'
brew 'loc'
brew 'mas'
brew 'mercurial'
brew 'mitmproxy'
brew 'mongodb'
brew 'mysql'
brew 'nvm'
brew 'postgresql'
brew 'rust'
cask 'java' # install java before scala
brew 'scala'
brew 'swiftlint'
brew 'thefuck'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watchexec'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'homebrew/science/opencv3'
brew 'homebrew/science/r'
brew 'homebrew/science/vtk'

cask 'xquartz'
cask 'bartender'
cask 'calibre'
cask 'charles'
cask 'daisydisk'
cask 'dash'
cask 'docker'
cask 'eclipse-ide'
cask 'etcher'
cask 'font-menlo-for-powerline'
cask 'gitup'
cask 'gpgtools'
cask 'icons8'
cask 'istat-menus'
cask 'keybase'
cask 'messenger'
cask 'ngrok'
cask 'obs'
cask 'paragon-ntfs'
cask 'paw'
cask 'robomongo'
cask 'screenflow'
cask 'skype'
cask 'softorino-youtube-converter'
cask 'spectacle'
cask 'spotify'
cask 'sqlpro-studio'
cask 'sublime-text'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'tower'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wireshark'

mas 'Apple Configurator 2', id: 1037126344
mas 'AutoMute', id: 1118136179
mas 'Deckset', id: 847496013
mas 'Deliveries', id: 924726344
mas 'GIF Brewery 3', id: 1081413713
mas 'Haskell', id: 841285201
mas 'HyperDock', id: 449830122
mas 'Notability', id: 736189492
mas 'Pixelmator', id: 407963104
mas 'Reeder', id: 880001334
mas 'Texpad', id: 458866234
mas 'Theine', id: 955848755
mas 'Tweetbot', id: 557168941
mas 'Wunderlist', id: 410628904
mas 'Xcode', id: 497799835
mas 'Yoink', id: 457622435
